import { ProjectorIcon, MonitorPlay, Wallpaper } from "lucide-react";

export const menus = [
  {
    name: "Project",
    url: "/#project",
    icon: ProjectorIcon,
  },
  {
    name: "Blog",
    url: "/blog",
    icon: Wallpaper,
  },
  {
    name: "Playgrounds",
    url: "/playgrounds",
    icon: MonitorPlay,
  },
];

export const technologies = [
  { label: "HTML", icon: "html.svg" },
  { label: "CSS", icon: "css.svg" },
  { label: "JavaScript", icon: "javascript.svg" },
  { label: "TypeScript", icon: "typescript.png" },
  { label: "PHP", icon: "php.svg" },
  { label: "React", icon: "react.svg" },
  { label: "Vite", icon: "vite.svg" },
  { label: "Vue.js", icon: "vuejs.svg" },
  { label: "Next.js", icon: "next.svg" },
  { label: "Laravel", icon: "laravel.svg" },
  { label: "Tailwind CSS", icon: "tailwind.svg" },
  { label: "Bootstrap", icon: "bootstrap.svg" },
  { label: "SASS", icon: "sass.svg" },
  { label: "Shadcn UI", icon: "shadcn.png" },
  { label: "Framer Motion", icon: "framer-motion.svg" },
  { label: "Material UI", icon: "material-ui.svg" },
  { label: "Chakra UI", icon: "chakra-ui.svg" },
  { label: "Express.js", icon: "express.svg" },
  { label: "Node.js", icon: "nodejs.svg" },
  { label: "MongoDB", icon: "mongodb.svg" },
  { label: "MySQL", icon: "mysql.png" },
  { label: "WordPress", icon: "wordpress.svg" },
  { label: "Elementor", icon: "elementor.png" },
  { label: "React Native", icon: "react-native.svg" },
  { label: "Git", icon: "git.svg" },
  { label: "GitHub", icon: "github.svg" },
  { label: "GitLab", icon: "gitlab.svg" },
  { label: "Figma", icon: "figma.svg" },
];

export const projects = [
  {
    name: "Islamic App",
    image: "quran-app.png",
    description: "",
    link: "https://azis-quran-app.vercel.app/",
    stacks: ["React", "TailwindCSS", "JavaScript", "DaisyUI", "Quran API"],
    landscape: false,
  },
  {
    name: "Movie Collection",
    image: "movie.png",
    description: "",
    link: "https://movie-collections.vercel.app/",
    stacks: ["React", "TailwindCSS", "JavaScript", "TMDB API"],
    landscape: true,
  },
  {
    name: "AI Chatbot",
    image: "chat-ai.png",
    description: "",
    link: "https://azis-openai.vercel.app/chat",
    stacks: ["React", "TailwindCSS", "DaisyUI", "Javascript", "OpenAI API"],
    landscape: true,
  },
  {
    name: "AI Image Generator",
    image: "image-generator.png",
    description: "",
    link: "https://azis-openai.vercel.app/create-post",
    stacks: [
      "React",
      "TailwindCSS",
      "DaisyUI",
      "Javascript",
      "OpenAI API",
      "Cloudinary",
      "NodeJS",
      "Express",
      "MongoDB",
    ],
    landscape: true,
  },
  {
    name: "Game News",
    image: "game-news.png",
    description: "",
    link: "https://azis-game-news.vercel.app/",
    stacks: ["React", "Javascript", "TailwindCSS", "DaisyUI", "Game News API"],
    landscape: true,
  },
  {
    name: "Playgrounds",
    image: "playgrounds.png",
    description: "",
    link: "https://github.com/",
    stacks: [
      "NextJS",
      "React",
      "TypeScript",
      "TailwindCSS",
      "FramerMotion",
      "HeadlessUI",
    ],
    landscape: true,
  },
  {
    name: "Game Collections",
    image: "quran-app.png",
    description: "",
    link: "https://games-collections.vercel.app/",
    stacks: ["React", "NextJS", "Javascript", "TailwindCSS", "RAWG API"],
    landscape: true,
  },
  {
    name: "ZeitPlan App (UI)",
    image: "zeitplan.png",
    description: "",
    link: "https://zeitplan-ui.vercel.app/",
    stacks: ["React", "Javascript", "TailwindCSS", "DaisyUI", "AOS"],
    landscape: false,
  },
  {
    name: "Game Events (UI)",
    image: "event-games.jpg",
    description: "",
    link: "https://azis-game-events.vercel.app/",
    stacks: ["React", "Javascript", "TailwindCSS", "DaisyUI"],
    landscape: false,
  },
];
