export const technologies = [
  { label: "HTML", icon: "html.svg" },
  { label: "CSS", icon: "css.svg" },
  { label: "JavaScript", icon: "javascript.svg" },
  { label: "TypeScript", icon: "typescript.png" },
  { label: "PHP", icon: "php.svg" },
  { label: "Laravel", icon: "laravel.svg" },
  { label: "React", icon: "react.svg" },
  { label: "React Native", icon: "react-native.svg" },
  { label: "Vue.js", icon: "vuejs.svg" },
  { label: "Next.js", icon: "next.svg" },
  { label: "Tailwind CSS", icon: "tailwind.svg" },
  { label: "Bootstrap", icon: "bootstrap.svg" },
  { label: "Shadcn UI", icon: "shadcn.png" },
  { label: "Express.js", icon: "express.svg" },
  { label: "Node.js", icon: "nodejs.svg" },
  { label: "MongoDB", icon: "mongodb.svg" },
  { label: "MySQL", icon: "mysql.png" },
  { label: "WordPress", icon: "wordpress.svg" },
  { label: "Elementor", icon: "elementor.png" },
  { label: "Git", icon: "git.svg" },
];
